import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/theme/provider";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/authProvider/authProvider";
import AuthSync from "./(protected)/dashboard/provider/provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DevSprint",
  description: "Generated by DevSprint",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        cz-shortcut-listen="true"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
            <AuthProvider>
                <div className="min-h-screen bg-background ">
                  <main>
                    <Toaster position="top-center" theme="system"/>
                    <AuthSync />
                    {children}
                  </main>
                </div>
            </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

